### ISSUE TITLE
Event Listener TH10 doesn't work.

### ISSUE THREAD

**Issue by driagi** [ottoszika/node-red-contrib-ewelink#110]
Hello,
after the last update, everything seemed to work. 
Suddenly, the Event Listener  stopped working....

**Comment by jbreslin** [comment]
Hi,

I have a similar issue with the listener using the 4-channel pro. I have not been successful in receiving notifications of state changes. 
I happy to provide any supportting info if it helps.

My solution uses Zigbee2MQTT and Mosquitto along with a remote node-red dashboard.

Happy to help if I can.

John

**Comment by driagi** [comment]
My issue is with TH10 and with Mini Sonoff. The Basic is OK.

**Comment by driagi** [comment]
On testing, I found that only the latest deploy  Listener device works, regardless of device types !

**Comment by AMalick** [comment]
Same issue here.. It seems to be related to the websocket timing out

Error thrown below...
UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 170)
(node:7740) UnhandledPromiseRejectionWarning: Error: Can't send data because WebSocket is not opened.
    at exports.throwIf (/home/pi/.node-red/node_modules/websocket-as-promised/src/utils.js:4:11)
    at WebSocketAsPromised.send (/home/pi/.node-red/node_modules/websocket-as-promised/src/index.js:248:5)
    at Timeout.setInterval [as _onTimeout] (/home/pi/.node-red/node_modules/ewelink-api/src/mixins/openWebSocket.js:39:17)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

**Comment by djpole** [comment]
Same problem  here. Raspberry running only node-red (no HA). All my house wired with sonoff basic and sockets S20 and S26. No one works with event listener. The only one that works is the Pow R2 installed in the main panel for reading power consumption. It´s the only module reporting status, volts, amps and watts. Once again all my domotic automations stopped and non working because based mainly in reading  status of the modules.

**Comment by djpole** [comment]
> On testing, I found that only the latest deploy Listener device works, regardless of device types !

Made some tests and can confirm this. With all my nodes disabled, testing each sonoff device individually the listener works, Sonoff basic works, sockets S20 and S26 work, 5V and 12V modules work, door sensors work.. everything works. But with 2 or more devices actived in your flows for monitoring, nothing works. So, I have to choose one device from all my house to automatize. Hope this problem solves soon, it´s a S***  to own an automatized house that you can´t automatize.

**Comment by vellad1** [comment]
same issue here :(

**Comment by driagi** [comment]
Any news about this issue?

**Comment by djpole** [comment]
4 months and no answer to this problem? Is the project abandoned? Someone with coding skills can continue developing ewelink integration node?

**Comment by nareso** [comment]
I got one solution.

Try this.
https://github.com/ottoszika/node-red-contrib-ewelink/issues/77#issuecomment-755246109

This will stabilize the connection and Event Listener work well.
