### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by otopenicity** [ottoszika/node-red-contrib-ewelink#142]
Hello! I'm trying to install
node-red-contrib-ewelink on rpi, but I can't.

pi@raspberrypi:~/.node-red $ npm install node-red-contrib-ewelink

> bufferutil@4.0.6 install /home/pi/.node-red/node_modules/bufferutil
> node-gyp-build

gyp ERR! configure error
gyp ERR! stack Error: Command failed: /usr/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:383:12)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at maybeClose (internal/child_process.js:1058:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:443:11)
gyp ERR! stack     at Socket.emit (events.js:400:28)
gyp ERR! stack     at Pipe.<anonymous> (net.js:686:12)
gyp ERR! System Linux 5.10.92-v8+
gyp ERR! command "/usr/bin/node" "/home/pi/.node-red/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/.node-red/node_modules/bufferutil
gyp ERR! node -v v14.19.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bufferutil@4.0.6 install: `node-gyp-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bufferutil@4.0.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2022-02-24T16_53_53_516Z-debug.log

thanks

**Comment by milandzuris** [comment]
same

**Comment by ramanvda** [comment]
Same


2023-12-24T10:26:28.694Z Installer : node-red-contrib-ewelink 2.0.0

2023-12-24T10:26:28.746Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-contrib-ewelink@2.0.0
2023-12-24T10:26:37.416Z [err] npm
2023-12-24T10:26:37.428Z [err]  
2023-12-24T10:26:37.430Z [err] WARN
2023-12-24T10:26:37.437Z [err]  config production Use `--omit=dev` instead.
2023-12-24T10:27:21.798Z [err] npm
2023-12-24T10:27:21.801Z [err]  
2023-12-24T10:27:21.802Z [err] ERR!
2023-12-24T10:27:21.804Z [err]  
2023-12-24T10:27:21.817Z [err] code ENOENT
2023-12-24T10:27:21.817Z [err] npm ERR! syscall spawn git
2023-12-24T10:27:21.817Z [err] npm ERR! path git
2023-12-24T10:27:21.825Z [err] npm
2023-12-24T10:27:21.826Z [err]  
2023-12-24T10:27:21.828Z [err] ERR!
2023-12-24T10:27:21.837Z [err]  errno -2
2023-12-24T10:27:21.864Z [err] npm
2023-12-24T10:27:21.865Z [err]  
2023-12-24T10:27:21.867Z [err] ERR!
2023-12-24T10:27:21.877Z [err]  enoent An unknown git error occurred
2023-12-24T10:27:21.877Z [err] npm ERR! enoent This is related to npm not being able to find a file.
2023-12-24T10:27:21.877Z [err] npm ERR! enoent 
2023-12-24T10:27:21.908Z [err] 
2023-12-24T10:27:21.911Z [err] npm
2023-12-24T10:27:21.912Z [err]  
2023-12-24T10:27:21.913Z [err] ERR!
2023-12-24T10:27:21.925Z [err]  A complete log of this run can be found in: /home/sdsdgssdb/.npm/_logs/2023-12-24T10_26_36_570Z-debug-0.log
2023-12-24T10:27:21.976Z rc=254
