### ISSUE TITLE
Fail to install on node-red 3.0.2

### ISSUE THREAD

**Issue by AlbertoRubinelli** [ottoszika/node-red-contrib-ewelink#160]
I have worked with this node with the previous version of node-red, (1 and 2) installed on some raspberry.
Now I'm setting up a new machine for node-red, with an x86 platform and node-red 3.0.2: I have installed a lot of nodes that I normally use, but only trying to install ewelink node, I receive an error message.
I've try some times, with the same effect.
The logs below have not help me to understand the problem.
Any idea ? Thanks in advance
----

log of failed installation on node-red screen

-----------------------------------------------------------
2022-12-31T16:22:54.298Z Install : node-red-contrib-ewelink 2.0.0

2022-12-31T16:22:54.626Z npm install --no-audit --no-update-notifier --no-fund --save --save-

prefix=~ --production --engine-strict node-red-contrib-ewelink@2.0.0
2022-12-31T16:22:56.951Z [err] npm
2022-12-31T16:22:56.953Z [err]  
2022-12-31T16:22:56.954Z [err] WARN config production Use `--omit=dev` instead.
2022-12-31T16:23:09.107Z [err] npm
2022-12-31T16:23:09.108Z [err]  ERR! code
2022-12-31T16:23:09.108Z [err]  ENOENT
2022-12-31T16:23:09.109Z [err] npm 
2022-12-31T16:23:09.109Z [err] ERR! syscall spawn git
2022-12-31T16:23:09.110Z [err] npm
2022-12-31T16:23:09.110Z [err]  ERR! path git
2022-12-31T16:23:09.114Z [err] npm 
2022-12-31T16:23:09.114Z [err] ERR! errno -2
2022-12-31T16:23:09.123Z [err] npm ERR!
2022-12-31T16:23:09.123Z [err]  enoent An unknown git error occurred
2022-12-31T16:23:09.123Z [err] npm
2022-12-31T16:23:09.123Z [err]  ERR! enoent This is related to npm not being able to find a file.
2022-12-31T16:23:09.123Z [err] npm
2022-12-31T16:23:09.124Z [err]  ERR! enoent 
2022-12-31T16:23:09.131Z [err] 
2022-12-31T16:23:09.132Z [err] npm 
2022-12-31T16:23:09.132Z [err] ERR!
2022-12-31T16:23:09.133Z [err]  A complete log of this run can be found in:
2022-12-31T16:23:09.133Z [err] npm
2022-12-31T16:23:09.133Z [err]  ERR!     /mnt/dietpi_userdata/node-red/.npm/_logs/2022-12-31T16_22_56_782Z-debug-.log
2022-12-31T16:23:09.173Z rc=254

 ─────────────────────────────────────────────────────
 DietPi v8.12.1 : 17:17 - Sat 12/31/22
 ─────────────────────────────────────────────────────
 - Device model : Native PC (x86_64)
 - CPU temp : 31 °C / 87 °F : Cool runnings
 - LAN IP : 192.168.5.2 (eth0)

debug log 
 
root@NodeRed:/mnt/dietpi_userdata/node-red/.npm/_logs# cat 2022-12-31T16_22_56_782Z-debug-0.log

0 verbose cli /usr/local/bin/node /usr/local/bin/npm
1 info using npm@9.2.0
2 info using node@v19.3.0
3 timing npm:load:whichnode Completed in 4ms
4 timing config:load:defaults Completed in 11ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 5ms
6 timing config:load:builtin Completed in 7ms
7 warn config production Use `--omit=dev` instead.
8 timing config:load:cli Completed in 18ms
9 timing config:load:env Completed in 1ms
10 timing config:load:project Completed in 42ms
11 timing config:load:file:/mnt/dietpi_userdata/node-red/.npmrc Completed in 1ms
12 timing config:load:user Completed in 3ms
13 timing config:load:file:/usr/local/etc/npmrc Completed in 1ms
14 timing config:load:global Completed in 1ms
15 timing config:load:setEnvs Completed in 6ms
16 timing config:load Completed in 94ms
17 timing npm:load:configload Completed in 94ms
18 timing npm:load:mkdirpcache Completed in 1ms
19 timing npm:load:mkdirplogs Completed in 1ms
20 verbose title npm install node-red-contrib-ewelink@2.0.0
21 verbose argv "install" "--no-audit" "--no-update-notifier" "--no-fund" "--save" "--save-prefix" "~" "--production" "--engine-strict" "node-red-contrib-ewelink@2.0.0"
22 timing npm:load:setTitle Completed in 10ms
23 timing config:load:flatten Completed in 19ms
24 timing npm:load:display Completed in 32ms
25 verbose logfile logs-max:10 dir:/mnt/dietpi_userdata/node-red/.npm/_logs/2022-12-31T16_22_56_782Z-
26 verbose logfile /mnt/dietpi_userdata/node-red/.npm/_logs/2022-12-31T16_22_56_782Z-debug-0.log
27 timing npm:load:logFile Completed in 29ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 175ms
31 silly logfile start cleaning logs, removing 1 files
32 timing config:load:flatten Completed in 4ms
33 timing arborist:ctor Completed in 5ms
34 silly logfile done cleaning log files
35 timing idealTree:init Completed in 2422ms
36 timing idealTree:userRequests Completed in 22ms
37 silly idealTree buildDeps
38 silly fetch manifest node-red-contrib-ewelink@2.0.0
39 timing arborist:ctor Completed in 1ms
40 http fetch GET 200 https://registry.npmjs.org/node-red-contrib-ewelink 2984ms (cache revalidated)
41 silly placeDep ROOT node-red-contrib-ewelink@2.0.0 OK for:  want: 2.0.0
42 silly fetch manifest ewelink-api@^3.1.1
43 http fetch GET 200 https://registry.npmjs.org/ewelink-api 755ms (cache revalidated)
44 timing idealTree:#root Completed in 3799ms
45 silly placeDep ROOT ewelink-api@3.1.1 OK for: node-red-contrib-ewelink@2.0.0 want: ^3.1.1
46 silly fetch manifest arpping@github:skydiver/arpping
47 silly fetch manifest crypto-js@^4.0.0
48 silly fetch manifest delay@^4.4.0
49 silly fetch manifest random@^2.2.0
50 silly fetch manifest websocket@^1.0.32
51 silly fetch manifest websocket-as-promised@^1.0.1
52 http fetch GET 200 https://registry.npmjs.org/crypto-js 858ms (cache revalidated)
53 http fetch GET 200 https://registry.npmjs.org/delay 1045ms (cache revalidated)
54 http fetch GET 200 https://registry.npmjs.org/websocket 1057ms (cache revalidated)
55 http fetch GET 200 https://registry.npmjs.org/random 1070ms (cache revalidated)
56 http fetch GET 200 https://registry.npmjs.org/websocket-as-promised 1078ms (cache revalidated)
57 timing idealTree:node_modules/node-red-contrib-ewelink Completed in 1123ms
58 silly placeDep node_modules/ewelink-api arpping@ OK for: ewelink-api@3.1.1 want: github:skydiver/arpping
59 silly placeDep ROOT crypto-js@4.1.1 OK for: ewelink-api@3.1.1 want: ^4.0.0
60 silly placeDep ROOT delay@4.4.1 OK for: ewelink-api@3.1.1 want: ^4.4.0
61 silly placeDep ROOT random@2.2.0 OK for: ewelink-api@3.1.1 want: ^2.2.0
62 silly placeDep ROOT websocket@1.0.34 OK for: ewelink-api@3.1.1 want: ^1.0.32
63 silly placeDep ROOT websocket-as-promised@1.1.0 OK for: ewelink-api@3.1.1 want: ^1.0.1
64 silly fetch manifest babel-runtime@^6.26.0
65 silly fetch manifest ow@^0.4.0
66 silly fetch manifest ow-lite@^0.0.2
67 silly fetch manifest seedrandom@^3.0.5
68 silly fetch manifest bufferutil@^4.0.1
69 silly fetch manifest es5-ext@^0.10.50
70 silly fetch manifest typedarray-to-buffer@^3.1.5
71 silly fetch manifest utf-8-validate@^5.0.2
72 silly fetch manifest yaeti@^0.0.6
73 silly fetch manifest chnl@^1.2.0
74 silly fetch manifest promise-controller@^1.0.0
75 silly fetch manifest promise.prototype.finally@^3.1.2
76 http fetch GET 200 https://registry.npmjs.org/typedarray-to-buffer 265ms (cache revalidated)
77 http fetch GET 200 https://registry.npmjs.org/es5-ext 327ms (cache revalidated)
78 http fetch GET 200 https://registry.npmjs.org/utf-8-validate 330ms (cache revalidated)
79 http fetch GET 200 https://registry.npmjs.org/babel-runtime 832ms (cache revalidated)
80 http fetch GET 200 https://registry.npmjs.org/seedrandom 862ms (cache revalidated)
81 http fetch GET 200 https://registry.npmjs.org/yaeti 884ms (cache revalidated)
82 http fetch GET 200 https://registry.npmjs.org/ow-lite 913ms (cache revalidated)
83 http fetch GET 200 https://registry.npmjs.org/promise.prototype.finally 980ms (cache revalidated)
84 http fetch GET 200 https://registry.npmjs.org/bufferutil 1009ms (cache revalidated)
85 http fetch GET 200 https://registry.npmjs.org/chnl 1017ms (cache revalidated)
86 http fetch GET 200 https://registry.npmjs.org/ow 1072ms (cache revalidated)
87 http fetch GET 200 https://registry.npmjs.org/promise-controller 1061ms (cache revalidated)
88 timing idealTree:node_modules/ewelink-api Completed in 1174ms
89 timing idealTree:node_modules/crypto-js Completed in 0ms
90 timing idealTree:node_modules/delay Completed in 0ms
91 silly placeDep ROOT babel-runtime@6.26.0 OK for: random@2.2.0 want: ^6.26.0
92 silly placeDep ROOT ow@0.4.0 OK for: random@2.2.0 want: ^0.4.0
93 silly placeDep ROOT ow-lite@0.0.2 OK for: random@2.2.0 want: ^0.0.2
94 silly placeDep ROOT seedrandom@3.0.5 OK for: random@2.2.0 want: ^3.0.5
95 silly fetch manifest core-js@^2.4.0
96 silly fetch manifest regenerator-runtime@^0.11.0
97 http fetch GET 200 https://registry.npmjs.org/regenerator-runtime 65ms (cache revalidated)
98 http fetch GET 200 https://registry.npmjs.org/core-js 741ms (cache revalidated)
99 timing idealTree:node_modules/random Completed in 834ms
100 silly placeDep ROOT core-js@2.6.12 OK for: babel-runtime@6.26.0 want: ^2.4.0
101 silly placeDep node_modules/babel-runtime regenerator-runtime@0.11.1 OK for: babel-runtime@6.26.0 want: ^0.11.0
102 timing idealTree:node_modules/babel-runtime Completed in 24ms
103 timing idealTree:node_modules/core-js Completed in 0ms
104 timing idealTree:node_modules/ow Completed in 2ms
105 timing idealTree:node_modules/ow-lite Completed in 1ms
106 timing idealTree:node_modules/seedrandom Completed in 0ms
107 silly placeDep ROOT bufferutil@4.0.7 OK for: websocket@1.0.34 want: ^4.0.1
108 silly placeDep ROOT es5-ext@0.10.62 OK for: websocket@1.0.34 want: ^0.10.50
109 silly placeDep ROOT typedarray-to-buffer@3.1.5 OK for: websocket@1.0.34 want: ^3.1.5
110 silly placeDep ROOT utf-8-validate@5.0.10 OK for: websocket@1.0.34 want: ^5.0.2
111 silly placeDep ROOT yaeti@0.0.6 OK for: websocket@1.0.34 want: ^0.0.6
112 silly fetch manifest es6-iterator@^2.0.3
113 silly fetch manifest es6-symbol@^3.1.3
114 silly fetch manifest next-tick@^1.1.0
115 http fetch GET 200 https://registry.npmjs.org/next-tick 85ms (cache revalidated)
116 http fetch GET 200 https://registry.npmjs.org/es6-iterator 797ms (cache revalidated)
117 http fetch GET 200 https://registry.npmjs.org/es6-symbol 814ms (cache revalidated)
118 timing idealTree:node_modules/websocket Completed in 878ms
119 timing idealTree:node_modules/bufferutil Completed in 1ms
120 silly placeDep ROOT es6-iterator@2.0.3 OK for: es5-ext@0.10.62 want: ^2.0.3
121 silly placeDep ROOT es6-symbol@3.1.3 OK for: es5-ext@0.10.62 want: ^3.1.3
122 silly placeDep ROOT next-tick@1.1.0 OK for: es5-ext@0.10.62 want: ^1.1.0
123 silly fetch manifest d@1
124 silly fetch manifest d@^1.0.1
125 silly fetch manifest ext@^1.1.2
126 http fetch GET 200 https://registry.npmjs.org/d 298ms (cache revalidated)
127 http fetch GET 200 https://registry.npmjs.org/ext 793ms (cache revalidated)
128 http fetch GET 200 https://registry.npmjs.org/d 814ms (cache revalidated)
129 timing idealTree:node_modules/es5-ext Completed in 852ms
130 silly placeDep ROOT d@1.0.1 OK for: es6-iterator@2.0.3 want: 1
131 silly fetch manifest type@^1.0.1
132 http fetch GET 200 https://registry.npmjs.org/type 744ms (cache revalidated)
133 timing idealTree:node_modules/es6-iterator Completed in 763ms
134 silly placeDep ROOT type@1.2.0 OK for: d@1.0.1 want: ^1.0.1
135 timing idealTree:node_modules/d Completed in 8ms
136 silly placeDep ROOT ext@1.7.0 OK for: es6-symbol@3.1.3 want: ^1.1.2
137 silly fetch manifest type@^2.7.2
138 timing idealTree:node_modules/es6-symbol Completed in 13ms
139 silly placeDep node_modules/ext type@2.7.2 OK for: ext@1.7.0 want: ^2.7.2
140 timing idealTree:node_modules/ext Completed in 8ms
141 timing idealTree:node_modules/next-tick Completed in 0ms
142 timing idealTree:node_modules/type Completed in 0ms
143 timing idealTree:node_modules/typedarray-to-buffer Completed in 1ms
144 timing idealTree:node_modules/utf-8-validate Completed in 0ms
145 silly placeDep ROOT chnl@1.2.0 OK for: websocket-as-promised@1.1.0 want: ^1.2.0
146 silly placeDep ROOT promise-controller@1.0.0 OK for: websocket-as-promised@1.1.0 want: ^1.0.0
147 silly placeDep ROOT promise.prototype.finally@3.1.4 OK for: websocket-as-promised@1.1.0 want: ^3.1.2
148 timing idealTree:node_modules/websocket-as-promised Completed in 29ms
149 timing idealTree:node_modules/chnl Completed in 0ms
150 timing idealTree:node_modules/promise-controller Completed in 0ms
151 timing idealTree:node_modules/promise.prototype.finally Completed in 1ms
152 timing idealTree:node_modules/yaeti Completed in 0ms
153 timing idealTree:node_modules/babel-runtime/node_modules/regenerator-runtime Completed in 0ms
154 timing idealTree:node_modules/ewelink-api/node_modules/arpping Completed in 0ms
155 timing idealTree:node_modules/ext/node_modules/type Completed in 0ms
156 timing idealTree:buildDeps Completed in 9531ms
157 timing idealTree:fixDepFlags Completed in 40ms
158 timing idealTree Completed in 12023ms
159 timing command:install Completed in 12051ms
160 verbose stack Error: An unknown git error occurred
160 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/@npmcli/git/lib/make-error.js:28:13)
160 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/@npmcli/git/lib/spawn.js:37:26
160 verbose stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
161 verbose cwd /mnt/dietpi_userdata/node-red
162 verbose Linux 5.10.0-20-amd64
163 verbose node v19.3.0
164 verbose npm  v9.2.0
165 error code ENOENT
166 error syscall spawn git
167 error path git
168 error errno -2
169 error enoent An unknown git error occurred
170 error enoent This is related to npm not being able to find a file.
170 error enoent
171 verbose exit -2
172 timing npm Completed in 12339ms
173 verbose unfinished npm timer reify 1672503777064
174 verbose unfinished npm timer reify:loadTrees 1672503777068
175 verbose code -2
176 error A complete log of this run can be found in:
176 error     /mnt/dietpi_userdata/node-red/.npm/_logs/2022-12-31T16_22_56_782Z-debug-0.log
--- end ---

**Comment by harish-jachak** [comment]
Same with me. on NodeRed 3.0.2
Earlier on same version it was installing but after sometime disappears automatically leaving nodes on flows us unknown nodes. I updated core-js to core-js@3.27.1. Now it wont install at all. 

Update: Jan 4, 2023 - Node is present in NodeRed now. Dont know how. May be everything was reset after a Pi reboot.

**Comment by AlbertoRubinelli** [comment]
The solution to my problem was very simple : install the github package.
apt install github
Now my node-red is working fine from weekes
